# Generated by Django 5.0.2 on 2024-03-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default='Emobilis', max_length=25, null=True),
        ),
    ]
