# Generated by Django 5.0.2 on 2024-03-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
